# GitHub Actions triggers based on the PR's and each commits on develop and master
name: "CI: Run tests"
on:
  workflow_dispatch:
  push:
    branches:
    - event/hass-dt-develop
    - hass-701-add-workflows

  pull_request:
    branches:
      - event/hass-dt-develop
      - hass-701-add-workflows
    types: [opened, synchronize, reopened]
  
permissions:
  contents: read
  pull-requests: write

env:
  DOCKERHUB_NAMESPACE: harbor.distributed-testing.org

jobs:
  determine_docker_org_and_tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Determine Docker organization and tag
        id: docker-org-and-tag
        uses: usdot-fhwa-stol/actions/docker-org-and-tag@main
    outputs:
      docker_org: ${{ steps.docker-org-and-tag.outputs.docker_organization }}
      docker_tag: ${{ steps.docker-org-and-tag.outputs.docker_image_tag }}

  build-dt-base-buildGeneral-core:
    runs-on: ubuntu-22.04
    needs: determine_docker_org_and_tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fetch required assets #TODO: Workflow mentions configuration for this
        working-directory: ./docker/build
        run: |
          chmod +x fetch-assets.sh
          ./fetch-assets.sh build-assets.env
          source build-assets.env
          chmod -R a+rX "$BUILD_DIR"

      - name: Build dt-base image
        working-directory: ./docker/build
        env:
          DOCKER_ORG: ${{ needs.determine_docker_org_and_tag.outputs.docker_org }}
          DOCKER_TAG: ${{ needs.determine_docker_org_and_tag.outputs.docker_tag }}
        run: |
          chmod +x build-image.sh
          ./build-image.sh base -v "$DOCKER_TAG"

      # - name: Build dt-build-general image
      #   working-directory: ./docker/build
      #   env:
      #     DOCKER_ORG: ${{ needs.determine_docker_org_and_tag.outputs.docker_org }}
      #     DOCKER_TAG: ${{ needs.determine_docker_org_and_tag.outputs.docker_tag }}
      #     USDOTFHWASTOL_TOKEN: ${{ secrets.GH_PAT }}
      #   run: |
      #     chmod +x build-image.sh
      #     ./build-image.sh build-general -v "$DOCKER_TAG"

      - name: Build dt-core image
        env:
          DOCKER_ORG: ${{ needs.determine_docker_org_and_tag.outputs.docker_org }}
          DOCKER_TAG: ${{ needs.determine_docker_org_and_tag.outputs.docker_tag }}
        run: |
          chmod +x scripts/build_tena_adapters/buildAllAdapters.sh
          cp ~/tenadev/INSTALL docker/build/lib/COPY
          chmod +x docker/build/build-image.sh
          ./docker/build/build-image.sh core -v "$DOCKER_TAG"
  
  build-dt-simdis:
    runs-on: ubuntu-22.04
    needs: [determine_docker_org_and_tag]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to DT Docker registry  ## TODO
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch required assets #TODO: Workflow mentions configuration for this
        working-directory: ./docker/build
        run: |
          chmod +x fetch-assets.sh
          ./fetch-assets.sh build-assets_simdis.env
          source build-assets_simdis.env
          chmod -R a+rX "$BUILD_DIR"

      - name: Build dt-simdis image
        working-directory: ./docker/build
        env:
          DOCKER_ORG: ${{ needs.determine_docker_org_and_tag.outputs.docker_org }}
          DOCKER_TAG: ${{ needs.determine_docker_org_and_tag.outputs.docker_tag }}
        run: |
          source build-assets_simdis.env && sudo DOCKER_BUILDKIT=1 \
          docker build --build-arg VERSION=$DOCKER_TAG --build-context assets="$BUILD_DIR" \
          -t $DOCKER_ORG/dt-simdis:$DOCKER_TAG . --progress=plain -f dt-simdis_Dockerfile